FROM openjdk:11

# Install necessary tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
    curl \
    maven \
    && rm -rf /var/lib/apt/lists/*n
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn package
CMD ["java", "-jar", "target/mon-application-jar-with-dependencies.jar"]
